<a href="https://colab.research.google.com/github/vikash-mahar/AI-MLNotes/blob/main/39Hyperparameter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
from google.colab import files

In [3]:
uploaded = files.upload()

Saving diabetes.csv to diabetes.csv

In [5]:
df = pd.read_csv('diabetes.csv')

In [6]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [7]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [8]:
x=df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [9]:
x

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [11]:
x= scaler.fit_transform(x)

In [12]:
x.shape

(768, 8)

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [14]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense,Dropout
!pip install -q -U keras-tuner
import keras_tuner as kt

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 1.9 MB/s eta 0:00:00

In [19]:
def build_model(hp):
  model = Sequential()
  num_layers = hp.Int('num_layers', min_value=1, max_value=10)

  for i in range(num_layers):
    if i == 0:
      model.add(Dense(hp.Int('units_' + str(i), min_value=8, max_value=128, step=8),
                      activation=hp.Choice('activation_' + str(i), values=['relu','tanh','sigmoid']),
                      input_dim=8))
    else:
      model.add(Dense(hp.Int('units_' + str(i), min_value=8, max_value=128, step=8),
                      activation=hp.Choice('activation_' + str(i), values=['relu','tanh','sigmoid'])
                    ))
    model.add(Dropout(hp.Choice('dropout_' + str(i), values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))

  model.add(Dense(1,activation='sigmoid'))
  model.compile(optimizer= hp.Choice('optimizer',values=['rmsprop','sgd','adam','adadelta','nadam']),
                loss='binary_crossentropy',
                metrics=['accuracy'])
  return model

In [20]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials =3,
                        directory='mydir',
                        project_name='final'
                        )

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [22]:
tuner.search(x_train,y_train,epochs=5,validation_data=(x_test,y_test))

Trial 3 Complete [00h 02m 26s]
val_accuracy: 0.6948052048683167

Best val_accuracy So Far: 0.6948052048683167
Total elapsed time: 00h 02m 28s

In [23]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 3,
 'units_0': 128,
 'activation_0': 'relu',
 'dropout_0': 0.4,
 'optimizer': 'sgd',
 'units_1': 32,
 'activation_1': 'sigmoid',
 'dropout_1': 0.1,
 'units_2': 112,
 'activation_2': 'sigmoid',
 'dropout_2': 0.5,
 'units_3': 120,
 'activation_3': 'relu',
 'dropout_3': 0.7,
 'units_4': 32,
 'activation_4': 'sigmoid',
 'dropout_4': 0.4}

In [24]:
model = tuner.get_best_models(num_models=1)[0]

In [26]:
model.fit(x_train,y_train,epochs=200,initial_epoch=6,validation_data=(x_test,y_test))

Epoch 7/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.5635 - loss: 0.7357 - val_accuracy: 0.6948 - val_loss: 0.6172
Epoch 8/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - accuracy: 0.6010 - loss: 0.6936 - val_accuracy: 0.6948 - val_loss: 0.6198
Epoch 9/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.5847 - loss: 0.6957 - val_accuracy: 0.6948 - val_loss: 0.6158
Epoch 10/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.5733 - loss: 0.7211 - val_accuracy: 0.6948 - val_loss: 0.6191
Epoch 11/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5733 - loss: 0.6936 - val_accuracy: 0.6948 - val_loss: 0.6160
Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6010 - loss: 0.6970 - val_accuracy: 0.6948 - val_loss: 0.6156
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5879 - loss: 0.7309 - val_accuracy: 0.6948 - val_loss: 0.6228
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5993 - loss: 0.6883 - val_accuracy: 0.6948 - val_loss: 0.6199
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5717 - loss: 0.7063 - val_accuracy: 0.6948 - val_loss: 0.6190
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5912 - loss: 0.6815 - val_accuracy: 0.6948 - val_loss: 0.6179
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6010 - loss: 0.6938 - val_accuracy: 0.6948 - val_loss: 0.6176
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6189 - loss: 0.6889 - val_accuracy: 0.6948 - val_loss: 0.6195
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6205 - loss: 0.6787 - val_accuracy: 0.6948 - val_loss: 0.6206
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6075 - loss: 0.6984 - val_accuracy: 0.6948 - val_loss: 0.6220
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5847 - loss: 0.6949 - val_accuracy: 0.6948 - val_loss: 0.6194
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6042 - loss: 0.7083 - val_accuracy: 0.6948 - val_loss: 0.6189
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6042 - loss: 0.6943 - val_accuracy: 0.6948 - val_loss: 0.6203
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6059 - loss: 0.6845 - val_accuracy: 0.6948 - val_loss: 0.6180
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6091 - loss: 0.6930 - val_accuracy: 0.6948 - val_loss: 0.6149
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5945 - loss: 0.6962 - val_accuracy: 0.6948 - val_loss: 0.6183
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5977 - loss: 0.7004 - val_accuracy: 0.6948 - val_loss: 0.6228
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5961 - loss: 0.6954 - val_accuracy: 0.6948 - val_loss: 0.6225
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5798 - loss: 0.6969 - val_accuracy: 0.6948 - val_loss: 0.6281
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5863 - loss: 0.6875 - val_accuracy: 0.6948 - val_loss: 0.6207
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6205 - loss: 0.6709 - val_accuracy: 0.6948 - val_loss: 0.6195
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5684 - loss: 0.6989 - val_accuracy: 0.6948 - val_loss: 0.6220
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5863 - loss: 0.6970 - val_accuracy: 0.6948 - val_loss: 0.6208
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6075 - loss: 0.6848 - val_accuracy: 0.6948 - val_loss: 0.6177
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6075 - loss: 0.6769 - val_accuracy: 0.6948 - val_loss: 0.6193
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5961 - loss: 0.6802 - val_accuracy: 0.6948 - val_loss: 0.6174
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5863 - loss: 0.7048 - val_accuracy: 0.6948 - val_loss: 0.6207
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6205 - loss: 0.6712 - val_accuracy: 0.6948 - val_loss: 0.6235
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6107 - loss: 0.6812 - val_accuracy: 0.6948 - val_loss: 0.6218
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5896 - loss: 0.7033 - val_accuracy: 0.6948 - val_loss: 0.6183
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5961 - loss: 0.6943 - val_accuracy: 0.6948 - val_loss: 0.6168
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6042 - loss: 0.6866 - val_accuracy: 0.6948 - val_loss: 0.6181
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6319 - loss: 0.6616 - val_accuracy: 0.6948 - val_loss: 0.6240
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5993 - loss: 0.6761 - val_accuracy: 0.6948 - val_loss: 0.6227
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6091 - loss: 0.6771 - val_accuracy: 0.6948 - val_loss: 0.6221
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6010 - loss: 0.6781 - val_accuracy: 0.6948 - val_loss: 0.6234
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5879 - loss: 0.6803 - val_accuracy: 0.6948 - val_loss: 0.6180
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6091 - loss: 0.6749 - val_accuracy: 0.6948 - val_loss: 0.6145
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6042 - loss: 0.6876 - val_accuracy: 0.6948 - val_loss: 0.6155
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6303 - loss: 0.6725 - val_accuracy: 0.6948 - val_loss: 0.6183
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6107 - loss: 0.6784 - val_accuracy: 0.6948 - val_loss: 0.6157
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6336 - loss: 0.6616 - val_accuracy: 0.6948 - val_loss: 0.6174
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6156 - loss: 0.6743 - val_accuracy: 0.6948 - val_loss: 0.6194
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6336 - loss: 0.6679 - val_accuracy: 0.6948 - val_loss: 0.6193
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6352 - loss: 0.6570 - val_accuracy: 0.6948 - val_loss: 0.6189
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6205 - loss: 0.6653 - val_accuracy: 0.6948 - val_loss: 0.6171
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6303 - loss: 0.6685 - val_accuracy: 0.6948 - val_loss: 0.6202
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6173 - loss: 0.6750 - val_accuracy: 0.6948 - val_loss: 0.6160
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6026 - loss: 0.6721 - val_accuracy: 0.6948 - val_loss: 0.6219
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6254 - loss: 0.6680 - val_accuracy: 0.6948 - val_loss: 0.6147
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6238 - loss: 0.6774 - val_accuracy: 0.6948 - val_loss: 0.6166
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6368 - loss: 0.6748 - val_accuracy: 0.6948 - val_loss: 0.6197
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6287 - loss: 0.6711 - val_accuracy: 0.6948 - val_loss: 0.6210
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6189 - loss: 0.6588 - val_accuracy: 0.6948 - val_loss: 0.6148
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6287 - loss: 0.6726 - val_accuracy: 0.6948 - val_loss: 0.6145
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6091 - loss: 0.6652 - val_accuracy: 0.6948 - val_loss: 0.6157
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6238 - loss: 0.6615 - val_accuracy: 0.6948 - val_loss: 0.6199
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6270 - loss: 0.6694 - val_accuracy: 0.6948 - val_loss: 0.6170
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6173 - loss: 0.6669 - val_accuracy: 0.6948 - val_loss: 0.6179
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6303 - loss: 0.6621 - val_accuracy: 0.6948 - val_loss: 0.6191
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6205 - loss: 0.6781 - val_accuracy: 0.6948 - val_loss: 0.6184
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6189 - loss: 0.6700 - val_accuracy: 0.6948 - val_loss: 0.6160
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6352 - loss: 0.6618 - val_accuracy: 0.6948 - val_loss: 0.6202
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6254 - loss: 0.6780 - val_accuracy: 0.6948 - val_loss: 0.6167
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6303 - loss: 0.6498 - val_accuracy: 0.6948 - val_loss: 0.6163
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6238 - loss: 0.6722 - val_accuracy: 0.6948 - val_loss: 0.6174
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6238 - loss: 0.6621 - val_accuracy: 0.6948 - val_loss: 0.6147
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6270 - loss: 0.6701 - val_accuracy: 0.6948 - val_loss: 0.6187
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6287 - loss: 0.6625 - val_accuracy: 0.6948 - val_loss: 0.6238
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6384 - loss: 0.6604 - val_accuracy: 0.6948 - val_loss: 0.6167
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6254 - loss: 0.6759 - val_accuracy: 0.6948 - val_loss: 0.6136
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6368 - loss: 0.6554 - val_accuracy: 0.6948 - val_loss: 0.6173
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6270 - loss: 0.6697 - val_accuracy: 0.6948 - val_loss: 0.6206
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6303 - loss: 0.6705 - val_accuracy: 0.6948 - val_loss: 0.6197
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6368 - loss: 0.6649 - val_accuracy: 0.6948 - val_loss: 0.6251
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6368 - loss: 0.6595 - val_accuracy: 0.6948 - val_loss: 0.6194
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6254 - loss: 0.6565 - val_accuracy: 0.6948 - val_loss: 0.6187
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6221 - loss: 0.6656 - val_accuracy: 0.6948 - val_loss: 0.6194
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6254 - loss: 0.6625 - val_accuracy: 0.6948 - val_loss: 0.6224
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.6319 - loss: 0.6593 - val_accuracy: 0.6948 - val_loss: 0.6160
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6368 - loss: 0.6659 - val_accuracy: 0.6948 - val_loss: 0.6184
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6352 - loss: 0.6581 - val_accuracy: 0.6948 - val_loss: 0.6142
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6450 - loss: 0.6515 - val_accuracy: 0.6948 - val_loss: 0.6194
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6287 - loss: 0.6562 - val_accuracy: 0.6948 - val_loss: 0.6235
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6238 - loss: 0.6587 - val_accuracy: 0.6948 - val_loss: 0.6153
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6368 - loss: 0.6503 - val_accuracy: 0.6948 - val_loss: 0.6218
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6384 - loss: 0.6742 - val_accuracy: 0.6948 - val_loss: 0.6215
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6417 - loss: 0.6543 - val_accuracy: 0.6948 - val_loss: 0.6220
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6319 - loss: 0.6542 - val_accuracy: 0.6948 - val_loss: 0.6186
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6221 - loss: 0.6677 - val_accuracy: 0.6948 - val_loss: 0.6164
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6466 - loss: 0.6503 - val_accuracy: 0.6948 - val_loss: 0.6165
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6336 - loss: 0.6577 - val_accuracy: 0.6948 - val_loss: 0.6216
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6368 - loss: 0.6602 - val_accuracy: 0.6948 - val_loss: 0.6159
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6433 - loss: 0.6631 - val_accuracy: 0.6948 - val_loss: 0.6199
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6319 - loss: 0.6621 - val_accuracy: 0.6948 - val_loss: 0.6158
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6303 - loss: 0.6595 - val_accuracy: 0.6948 - val_loss: 0.6143
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6417 - loss: 0.6617 - val_accuracy: 0.6948 - val_loss: 0.6185
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6368 - loss: 0.6625 - val_accuracy: 0.6948 - val_loss: 0.6156
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6368 - loss: 0.6709 - val_accuracy: 0.6948 - val_loss: 0.6192
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6319 - loss: 0.6651 - val_accuracy: 0.6948 - val_loss: 0.6177
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6352 - loss: 0.6539 - val_accuracy: 0.6948 - val_loss: 0.6185
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6384 - loss: 0.6636 - val_accuracy: 0.6948 - val_loss: 0.6188
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6336 - loss: 0.6592 - val_accuracy: 0.6948 - val_loss: 0.6154
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6352 - loss: 0.6662 - val_accuracy: 0.6948 - val_loss: 0.6243
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6433 - loss: 0.6666 - val_accuracy: 0.6948 - val_loss: 0.6178
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6401 - loss: 0.6558 - val_accuracy: 0.6948 - val_loss: 0.6159
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6450 - loss: 0.6556 - val_accuracy: 0.6948 - val_loss: 0.6182
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6319 - loss: 0.6614 - val_accuracy: 0.6948 - val_loss: 0.6245
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6319 - loss: 0.6570 - val_accuracy: 0.6948 - val_loss: 0.6194
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6384 - loss: 0.6558 - val_accuracy: 0.6948 - val_loss: 0.6164
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6384 - loss: 0.6559 - val_accuracy: 0.6948 - val_loss: 0.6156
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6352 - loss: 0.6640 - val_accuracy: 0.6948 - val_loss: 0.6224
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6401 - loss: 0.6550 - val_accuracy: 0.6948 - val_loss: 0.6204
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6384 - loss: 0.6578 - val_accuracy: 0.6948 - val_loss: 0.6206
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6401 - loss: 0.6571 - val_accuracy: 0.6948 - val_loss: 0.6143
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6384 - loss: 0.6575 - val_accuracy: 0.6948 - val_loss: 0.6145
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6401 - loss: 0.6580 - val_accuracy: 0.6948 - val_loss: 0.6161
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6401 - loss: 0.6639 - val_accuracy: 0.6948 - val_loss: 0.6193
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6450 - loss: 0.6512 - val_accuracy: 0.6948 - val_loss: 0.6147
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6401 - loss: 0.6588 - val_accuracy: 0.6948 - val_loss: 0.6149
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6319 - loss: 0.6563 - val_accuracy: 0.6948 - val_loss: 0.6137
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6401 - loss: 0.6595 - val_accuracy: 0.6948 - val_loss: 0.6190
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6352 - loss: 0.6563 - val_accuracy: 0.6948 - val_loss: 0.6175
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6368 - loss: 0.6573 - val_accuracy: 0.6948 - val_loss: 0.6206
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6417 - loss: 0.6609 - val_accuracy: 0.6948 - val_loss: 0.6169
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6352 - loss: 0.6611 - val_accuracy: 0.6948 - val_loss: 0.6217
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6384 - loss: 0.6572 - val_accuracy: 0.6948 - val_loss: 0.6190
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6384 - loss: 0.6573 - val_accuracy: 0.6948 - val_loss: 0.6138
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6401 - loss: 0.6557 - val_accuracy: 0.6948 - val_loss: 0.6193
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6384 - loss: 0.6607 - val_accuracy: 0.6948 - val_loss: 0.6236
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6303 - loss: 0.6517 - val_accuracy: 0.6948 - val_loss: 0.6238
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6417 - loss: 0.6616 - val_accuracy: 0.6948 - val_loss: 0.6170
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6401 - loss: 0.6581 - val_accuracy: 0.6948 - val_loss: 0.6147
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6401 - loss: 0.6649 - val_accuracy: 0.6948 - val_loss: 0.6186
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6352 - loss: 0.6532 - val_accuracy: 0.6948 - val_loss: 0.6182
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6384 - loss: 0.6584 - val_accuracy: 0.6948 - val_loss: 0.6232
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6368 - loss: 0.6660 - val_accuracy: 0.6948 - val_loss: 0.6148
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6384 - loss: 0.6585 - val_accuracy: 0.6948 - val_loss: 0.6155
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6368 - loss: 0.6630 - val_accuracy: 0.6948 - val_loss: 0.6159
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6401 - loss: 0.6515 - val_accuracy: 0.6948 - val_loss: 0.6242
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6384 - loss: 0.6544 - val_accuracy: 0.6948 - val_loss: 0.6188
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6384 - loss: 0.6573 - val_accuracy: 0.6948 - val_loss: 0.6155
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6417 - loss: 0.6544 - val_accuracy: 0.6948 - val_loss: 0.6225
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6401 - loss: 0.6575 - val_accuracy: 0.6948 - val_loss: 0.6193
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6401 - loss: 0.6556 - val_accuracy: 0.6948 - val_loss: 0.6165
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6368 - loss: 0.6578 - val_accuracy: 0.6948 - val_loss: 0.6177
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6384 - loss: 0.6538 - val_accuracy: 0.6948 - val_loss: 0.6238
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6401 - loss: 0.6630 - val_accuracy: 0.6948 - val_loss: 0.6225
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6384 - loss: 0.6576 - val_accuracy: 0.6948 - val_loss: 0.6181
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6401 - loss: 0.6575 - val_accuracy: 0.6948 - val_loss: 0.6204
Epoch 161/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6384 - loss: 0.6532 - val_accuracy: 0.6948 - val_loss: 0.6174
Epoch 162/200